"""add project image and social links

Revision ID: 3f49eb562641
Revises: e067871fd3d4
Create Date: 2026-06-22 10:35:59.866845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f49eb562641'
down_revision = 'e067871fd3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('site_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kaggle_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_profile', schema=None) as batch_op:
        batch_op.drop_column('kaggle_url')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('whatsapp_url')
        batch_op.drop_column('telegram_url')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
