"""add leetcode url

Revision ID: d1734800e3e7
Revises: 3f49eb562641
Create Date: 2026-06-23 15:16:29.437503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1734800e3e7'
down_revision = '3f49eb562641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leetcode_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_profile', schema=None) as batch_op:
        batch_op.drop_column('leetcode_url')

    # ### end Alembic commands ###
